-- Migration 0004 -- normalize headlines.tags through the canonical alias map.
-- SIG-181 (B4 of the SIG-174 plan).
--
-- Generated from config/canonical_tags.json. Do not edit this file by hand --
-- update the JSON and re-run docs/migrations/gen_sql_migration.py instead.
--
-- Runs in phpMyAdmin / mysql client. No CLI, no SSH, no stored procedure,
-- no CREATE ROUTINE privilege required.
--
-- Idempotence:
--   * tag_aliases create / populate is no-op on re-run.
--   * The headlines.tags case-fold pre-pass is no-op once tags is already lowercase.
--   * Each per-alias UPDATE is guarded by FIND_IN_SET(<alias>, tags), which
--     returns 0 after the first successful apply, so re-runs update 0 rows.
--
-- Case-sensitivity defect handled here (board feedback, 2026-06-04 verify):
--   FIND_IN_SET is collation-insensitive on the standard ci collations, but
--   REPLACE is byte-exact. Without normalization, mixed-case alias tags
--   ('IIT', 'tFUS', 'NDE') would pass the FIND_IN_SET guard but be skipped
--   by REPLACE, leaving the row mid-normalization. We lower-case headlines.tags
--   up front so every subsequent REPLACE matches every tag the guard sees.
--
-- Collation alignment (board correction, 2026-06-05 verify):
--   information_schema ground truth: headlines.tags is utf8mb4_unicode_ci
--   (the 249-row production table holds non-ASCII content). tag_aliases is
--   pinned here to match, so cross-table joins (FIND_IN_SET(a.alias_slug,
--   h.tags), and the clustering queries the SSCI Digest Editor will run later)
--   do not need an explicit COLLATE clause. Step 1b retro-fixes any existing
--   deployment that picked up a different collation from the server default.
--   (The earlier PR #12 had this inverted -- pinning to general_ci preserved
--   the very mismatch the step was supposed to remove.)
--
-- Dedup during migration: for each alias -> canonical, we run two UPDATEs.
--   (a) If a row contains BOTH the alias and the canonical, delete the alias
--       (so 'memristor,neuromorphic' becomes 'neuromorphic', not
--       'neuromorphic,neuromorphic').
--   (b) Otherwise, REPLACE the alias with the canonical in place.
-- Both UPDATEs are FIND_IN_SET-guarded, so each is independently a no-op
-- once it has been applied, and the (a)/(b) split is mutually exclusive on
-- any given row.

USE oddimfjz_headlinestore;

-- ---------------------------------------------------------------------------
-- 1. tag_aliases table.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS tag_aliases (
  alias_slug     VARCHAR(100) NOT NULL,
  canonical_slug VARCHAR(100) NOT NULL,
  PRIMARY KEY (alias_slug),
  KEY idx_canonical_slug (canonical_slug)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 1b. Retro-fix the collation in case the table was created earlier under a
--     different server default (the original prod apply on 2026-06-04 picked
--     up utf8mb4_general_ci against a headlines table on utf8mb4_unicode_ci,
--     which made cross-table FIND_IN_SET fail without explicit COLLATE clauses.)
--     No-op when already aligned.
ALTER TABLE tag_aliases CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- ---------------------------------------------------------------------------
-- 2. Populate tag_aliases. REPLACE INTO is idempotent: the primary key is the
--    alias slug, so re-runs overwrite identical rows in place.
-- ---------------------------------------------------------------------------
REPLACE INTO tag_aliases (alias_slug, canonical_slug) VALUES
  ('adaptive', 'memory-systems'),
  ('agents', 'agents'),
  ('aging', 'medical-ai'),
  ('ai', 'ai'),
  ('ai-agent', 'agents'),
  ('ai-economics', 'energy'),
  ('ai-evaluation', 'ai-evaluation'),
  ('ai-for-math', 'ai-for-math'),
  ('ai-for-science', 'ai-for-science'),
  ('ai-hardware', 'neuromorphic'),
  ('ai-robotics', 'robotics'),
  ('ai-safety', 'ai-safety'),
  ('algorithm-discovery', 'ai-for-math'),
  ('algorithms', 'ai-for-math'),
  ('alignment', 'ai-safety'),
  ('alphaevolve', 'ai-for-math'),
  ('alphafold', 'proteins'),
  ('altermagnetism', 'physics'),
  ('anthropic', 'ai-safety'),
  ('applied-math', 'ai-for-math'),
  ('astrobiology', 'space'),
  ('autonomous-labs', 'ai-for-science'),
  ('bci', 'bci'),
  ('benchmarks', 'ai-evaluation'),
  ('bio-computing', 'biocomputing'),
  ('bio-inspired', 'neuromorphic'),
  ('biocomputing', 'biocomputing'),
  ('biohybrid', 'biocomputing'),
  ('biology', 'medical-ai'),
  ('biophysics', 'medical-ai'),
  ('biotech', 'medical-ai'),
  ('brain-computer-interface', 'bci'),
  ('brain-inspired', 'neuro-symbolic'),
  ('brain-machine-interface', 'bci'),
  ('brain-stimulation', 'bci'),
  ('brownian-motion', 'physics'),
  ('cancer', 'medical-ai'),
  ('cell-biology', 'medical-ai'),
  ('chain-of-thought', 'ai-safety'),
  ('chaos', 'physics'),
  ('chaos-prediction', 'physics'),
  ('chemistry', 'chemistry'),
  ('circuit-depth', 'quantum-computing'),
  ('climate', 'physics-informed-ml'),
  ('climate-modeling', 'physics-informed-ml'),
  ('clinical-trials', 'medical-ai'),
  ('cognition', 'reasoning'),
  ('coma', 'medical-ai'),
  ('compiler', 'ai-for-math'),
  ('computing', 'ai'),
  ('condensed-matter', 'physics'),
  ('consciousness', 'consciousness'),
  ('control-theory', 'reasoning'),
  ('data-storage', 'genomics'),
  ('democratization', 'energy'),
  ('dielectric', 'physics'),
  ('diffusion-model', 'generative-models'),
  ('diffusion-models', 'generative-models'),
  ('dna', 'genomics'),
  ('dna-robots', 'molecular-computing'),
  ('dna-storage', 'genomics'),
  ('drug-delivery', 'medical-ai'),
  ('drug-discovery', 'medical-ai'),
  ('dusty-plasma', 'physics'),
  ('energy', 'energy'),
  ('energy-efficiency', 'energy'),
  ('epigenetics', 'genomics'),
  ('ev', 'physics'),
  ('evaluation', 'ai-evaluation'),
  ('evolutionary-ai', 'ai-for-math'),
  ('exoplanets', 'space'),
  ('extreme-computing', 'energy'),
  ('fungal-computing', 'biocomputing'),
  ('generative-ai', 'generative-models'),
  ('generative-models', 'generative-models'),
  ('genetic-circuits', 'synthetic-biology'),
  ('genomics', 'genomics'),
  ('godel', 'ai-for-math'),
  ('goedel', 'ai-for-math'),
  ('goodfire', 'mechanistic-interpretability'),
  ('gpt', 'gpt'),
  ('graph-neural-network', 'generative-models'),
  ('graphene', 'materials-science'),
  ('hardware', 'neuromorphic'),
  ('health', 'medical-ai'),
  ('hybrid', 'neuro-symbolic'),
  ('iit', 'consciousness'),
  ('inner-speech', 'reasoning'),
  ('insilico-medicine', 'medical-ai'),
  ('interpretability', 'mechanistic-interpretability'),
  ('isomorphic-labs', 'proteins'),
  ('jevons-paradox', 'energy'),
  ('kv-cache', 'llm'),
  ('lip-sync', 'generative-models'),
  ('llm', 'llm'),
  ('llms', 'llm'),
  ('longevity', 'medical-ai'),
  ('lucid-dreaming', 'bci'),
  ('machine-learning', 'ai'),
  ('magnets', 'physics'),
  ('materials', 'materials-science'),
  ('materials-science', 'materials-science'),
  ('math', 'ai-for-math'),
  ('mathematical-creativity', 'ai-for-math'),
  ('mathematics', 'ai-for-math'),
  ('mechanistic-interpretability', 'mechanistic-interpretability'),
  ('medical-ai', 'medical-ai'),
  ('memory', 'memory-systems'),
  ('memory-chip', 'memory-systems'),
  ('memory-compute', 'memory-systems'),
  ('memory-systems', 'memory-systems'),
  ('memristor', 'neuromorphic'),
  ('ml', 'ai'),
  ('molecular-computing', 'molecular-computing'),
  ('multitasking', 'reasoning'),
  ('mycelium', 'biocomputing'),
  ('nanoengineering', 'materials-science'),
  ('nanotechnology', 'materials-science'),
  ('nde', 'consciousness'),
  ('near-death-experience', 'consciousness'),
  ('neural-network', 'ai'),
  ('neural-networks', 'ai'),
  ('neuro-symbolic', 'neuro-symbolic'),
  ('neuro-symbolic-ai', 'neuro-symbolic'),
  ('neurology', 'medical-ai'),
  ('neuromorphic', 'neuromorphic'),
  ('neurons', 'biocomputing'),
  ('neuroprosthetics', 'bci'),
  ('neuroscience', 'neuroscience'),
  ('neurostimulation', 'bci'),
  ('nisq', 'quantum-computing'),
  ('noise', 'quantum-computing'),
  ('openai', 'gpt'),
  ('openevolve', 'ai-for-math'),
  ('optics', 'physics'),
  ('optimization', 'ai-for-math'),
  ('organoids', 'biocomputing'),
  ('panpsychism', 'consciousness'),
  ('panspermia', 'space'),
  ('particle-accelerator', 'physics'),
  ('pattern-matching', 'reasoning'),
  ('pde', 'physics-informed-ml'),
  ('peer-review', 'ai-evaluation'),
  ('philosophy', 'consciousness'),
  ('philosophy-of-mind', 'consciousness'),
  ('photonic-computing', 'neuromorphic'),
  ('photosynthesis', 'quantum-biology'),
  ('physics', 'physics'),
  ('physics-informed', 'physics-informed-ml'),
  ('physics-informed-ml', 'physics-informed-ml'),
  ('planning', 'reasoning'),
  ('plasma', 'physics'),
  ('polymers', 'materials-science'),
  ('programming-languages', 'ai-for-math'),
  ('protein-design', 'proteins'),
  ('proteins', 'proteins'),
  ('quantum', 'quantum-computing'),
  ('quantum-advantage', 'quantum-computing'),
  ('quantum-biology', 'quantum-biology'),
  ('quantum-computing', 'quantum-computing'),
  ('quantum-noise', 'quantum-computing'),
  ('quantum-physics', 'physics'),
  ('qubit', 'quantum-computing'),
  ('qubits', 'quantum-computing'),
  ('rare-earth', 'physics'),
  ('reasoning', 'reasoning'),
  ('research', 'ai-for-science'),
  ('reward-hacking', 'ai-safety'),
  ('robotics', 'robotics'),
  ('safety', 'ai-safety'),
  ('science', 'ai-for-science'),
  ('science-automation', 'ai-for-science'),
  ('scientific-computing', 'ai-for-science'),
  ('scientific-discovery', 'ai-for-science'),
  ('scientific-ml', 'ai-for-science'),
  ('self-supervised-learning', 'generative-models'),
  ('seti', 'space'),
  ('simulation-hypothesis', 'consciousness'),
  ('space', 'space'),
  ('spiking-neural-network', 'neuromorphic'),
  ('stdp', 'neuromorphic'),
  ('swarm-robotics', 'robotics'),
  ('swarms', 'robotics'),
  ('synthetic-biology', 'synthetic-biology'),
  ('tfus', 'bci'),
  ('thermodynamics', 'physics'),
  ('tryptophan', 'neuroscience'),
  ('ultrasound', 'bci'),
  ('uncanny-valley', 'generative-models'),
  ('wearable', 'bci'),
  ('working-memory', 'neuroscience');

-- ---------------------------------------------------------------------------
-- 2b. Case-fold headlines.tags so REPLACE matches every alias FIND_IN_SET
--     sees. BINARY makes the inequality byte-exact (the column's default
--     collation would treat 'IIT' and 'iit' as equal and skip the update).
--     Re-runs are no-ops because tags is already lowercase after the first
--     successful apply.
-- ---------------------------------------------------------------------------
UPDATE headlines
   SET tags = LOWER(tags)
 WHERE tags IS NOT NULL
   AND BINARY tags <> BINARY LOWER(tags);

-- ---------------------------------------------------------------------------
-- 3. Rewrite tags. Two UPDATEs per non-trivial alias (alias != canonical):
--    (a) BOTH alias and canonical present -> delete the alias (dedup).
--    (b) Only the alias is present -> REPLACE alias with canonical.
--    Comma-anchored everywhere so 'kv-cache' never matches 'mega-kv-cache-x'.
--    Both are FIND_IN_SET-guarded so they are independently no-ops on re-run.
-- ---------------------------------------------------------------------------
-- adaptive -> memory-systems
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM
               REPLACE(
                 REPLACE(CONCAT(',', tags, ','), ',adaptive,', ','),
                 ',,', ','))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('adaptive', tags)
   AND FIND_IN_SET('memory-systems', tags);
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM REPLACE(CONCAT(',', tags, ','), ',adaptive,', ',memory-systems,'))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('adaptive', tags)
   AND NOT FIND_IN_SET('memory-systems', tags);
-- aging -> medical-ai
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM
               REPLACE(
                 REPLACE(CONCAT(',', tags, ','), ',aging,', ','),
                 ',,', ','))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('aging', tags)
   AND FIND_IN_SET('medical-ai', tags);
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM REPLACE(CONCAT(',', tags, ','), ',aging,', ',medical-ai,'))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('aging', tags)
   AND NOT FIND_IN_SET('medical-ai', tags);
-- ai-agent -> agents
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM
               REPLACE(
                 REPLACE(CONCAT(',', tags, ','), ',ai-agent,', ','),
                 ',,', ','))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('ai-agent', tags)
   AND FIND_IN_SET('agents', tags);
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM REPLACE(CONCAT(',', tags, ','), ',ai-agent,', ',agents,'))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('ai-agent', tags)
   AND NOT FIND_IN_SET('agents', tags);
-- ai-economics -> energy
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM
               REPLACE(
                 REPLACE(CONCAT(',', tags, ','), ',ai-economics,', ','),
                 ',,', ','))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('ai-economics', tags)
   AND FIND_IN_SET('energy', tags);
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM REPLACE(CONCAT(',', tags, ','), ',ai-economics,', ',energy,'))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('ai-economics', tags)
   AND NOT FIND_IN_SET('energy', tags);
-- ai-hardware -> neuromorphic
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM
               REPLACE(
                 REPLACE(CONCAT(',', tags, ','), ',ai-hardware,', ','),
                 ',,', ','))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('ai-hardware', tags)
   AND FIND_IN_SET('neuromorphic', tags);
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM REPLACE(CONCAT(',', tags, ','), ',ai-hardware,', ',neuromorphic,'))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('ai-hardware', tags)
   AND NOT FIND_IN_SET('neuromorphic', tags);
-- ai-robotics -> robotics
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM
               REPLACE(
                 REPLACE(CONCAT(',', tags, ','), ',ai-robotics,', ','),
                 ',,', ','))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('ai-robotics', tags)
   AND FIND_IN_SET('robotics', tags);
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM REPLACE(CONCAT(',', tags, ','), ',ai-robotics,', ',robotics,'))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('ai-robotics', tags)
   AND NOT FIND_IN_SET('robotics', tags);
-- algorithm-discovery -> ai-for-math
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM
               REPLACE(
                 REPLACE(CONCAT(',', tags, ','), ',algorithm-discovery,', ','),
                 ',,', ','))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('algorithm-discovery', tags)
   AND FIND_IN_SET('ai-for-math', tags);
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM REPLACE(CONCAT(',', tags, ','), ',algorithm-discovery,', ',ai-for-math,'))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('algorithm-discovery', tags)
   AND NOT FIND_IN_SET('ai-for-math', tags);
-- algorithms -> ai-for-math
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM
               REPLACE(
                 REPLACE(CONCAT(',', tags, ','), ',algorithms,', ','),
                 ',,', ','))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('algorithms', tags)
   AND FIND_IN_SET('ai-for-math', tags);
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM REPLACE(CONCAT(',', tags, ','), ',algorithms,', ',ai-for-math,'))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('algorithms', tags)
   AND NOT FIND_IN_SET('ai-for-math', tags);
-- alignment -> ai-safety
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM
               REPLACE(
                 REPLACE(CONCAT(',', tags, ','), ',alignment,', ','),
                 ',,', ','))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('alignment', tags)
   AND FIND_IN_SET('ai-safety', tags);
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM REPLACE(CONCAT(',', tags, ','), ',alignment,', ',ai-safety,'))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('alignment', tags)
   AND NOT FIND_IN_SET('ai-safety', tags);
-- alphaevolve -> ai-for-math
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM
               REPLACE(
                 REPLACE(CONCAT(',', tags, ','), ',alphaevolve,', ','),
                 ',,', ','))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('alphaevolve', tags)
   AND FIND_IN_SET('ai-for-math', tags);
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM REPLACE(CONCAT(',', tags, ','), ',alphaevolve,', ',ai-for-math,'))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('alphaevolve', tags)
   AND NOT FIND_IN_SET('ai-for-math', tags);
-- alphafold -> proteins
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM
               REPLACE(
                 REPLACE(CONCAT(',', tags, ','), ',alphafold,', ','),
                 ',,', ','))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('alphafold', tags)
   AND FIND_IN_SET('proteins', tags);
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM REPLACE(CONCAT(',', tags, ','), ',alphafold,', ',proteins,'))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('alphafold', tags)
   AND NOT FIND_IN_SET('proteins', tags);
-- altermagnetism -> physics
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM
               REPLACE(
                 REPLACE(CONCAT(',', tags, ','), ',altermagnetism,', ','),
                 ',,', ','))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('altermagnetism', tags)
   AND FIND_IN_SET('physics', tags);
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM REPLACE(CONCAT(',', tags, ','), ',altermagnetism,', ',physics,'))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('altermagnetism', tags)
   AND NOT FIND_IN_SET('physics', tags);
-- anthropic -> ai-safety
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM
               REPLACE(
                 REPLACE(CONCAT(',', tags, ','), ',anthropic,', ','),
                 ',,', ','))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('anthropic', tags)
   AND FIND_IN_SET('ai-safety', tags);
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM REPLACE(CONCAT(',', tags, ','), ',anthropic,', ',ai-safety,'))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('anthropic', tags)
   AND NOT FIND_IN_SET('ai-safety', tags);
-- applied-math -> ai-for-math
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM
               REPLACE(
                 REPLACE(CONCAT(',', tags, ','), ',applied-math,', ','),
                 ',,', ','))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('applied-math', tags)
   AND FIND_IN_SET('ai-for-math', tags);
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM REPLACE(CONCAT(',', tags, ','), ',applied-math,', ',ai-for-math,'))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('applied-math', tags)
   AND NOT FIND_IN_SET('ai-for-math', tags);
-- astrobiology -> space
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM
               REPLACE(
                 REPLACE(CONCAT(',', tags, ','), ',astrobiology,', ','),
                 ',,', ','))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('astrobiology', tags)
   AND FIND_IN_SET('space', tags);
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM REPLACE(CONCAT(',', tags, ','), ',astrobiology,', ',space,'))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('astrobiology', tags)
   AND NOT FIND_IN_SET('space', tags);
-- autonomous-labs -> ai-for-science
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM
               REPLACE(
                 REPLACE(CONCAT(',', tags, ','), ',autonomous-labs,', ','),
                 ',,', ','))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('autonomous-labs', tags)
   AND FIND_IN_SET('ai-for-science', tags);
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM REPLACE(CONCAT(',', tags, ','), ',autonomous-labs,', ',ai-for-science,'))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('autonomous-labs', tags)
   AND NOT FIND_IN_SET('ai-for-science', tags);
-- benchmarks -> ai-evaluation
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM
               REPLACE(
                 REPLACE(CONCAT(',', tags, ','), ',benchmarks,', ','),
                 ',,', ','))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('benchmarks', tags)
   AND FIND_IN_SET('ai-evaluation', tags);
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM REPLACE(CONCAT(',', tags, ','), ',benchmarks,', ',ai-evaluation,'))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('benchmarks', tags)
   AND NOT FIND_IN_SET('ai-evaluation', tags);
-- bio-computing -> biocomputing
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM
               REPLACE(
                 REPLACE(CONCAT(',', tags, ','), ',bio-computing,', ','),
                 ',,', ','))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('bio-computing', tags)
   AND FIND_IN_SET('biocomputing', tags);
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM REPLACE(CONCAT(',', tags, ','), ',bio-computing,', ',biocomputing,'))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('bio-computing', tags)
   AND NOT FIND_IN_SET('biocomputing', tags);
-- bio-inspired -> neuromorphic
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM
               REPLACE(
                 REPLACE(CONCAT(',', tags, ','), ',bio-inspired,', ','),
                 ',,', ','))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('bio-inspired', tags)
   AND FIND_IN_SET('neuromorphic', tags);
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM REPLACE(CONCAT(',', tags, ','), ',bio-inspired,', ',neuromorphic,'))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('bio-inspired', tags)
   AND NOT FIND_IN_SET('neuromorphic', tags);
-- biohybrid -> biocomputing
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM
               REPLACE(
                 REPLACE(CONCAT(',', tags, ','), ',biohybrid,', ','),
                 ',,', ','))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('biohybrid', tags)
   AND FIND_IN_SET('biocomputing', tags);
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM REPLACE(CONCAT(',', tags, ','), ',biohybrid,', ',biocomputing,'))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('biohybrid', tags)
   AND NOT FIND_IN_SET('biocomputing', tags);
-- biology -> medical-ai
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM
               REPLACE(
                 REPLACE(CONCAT(',', tags, ','), ',biology,', ','),
                 ',,', ','))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('biology', tags)
   AND FIND_IN_SET('medical-ai', tags);
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM REPLACE(CONCAT(',', tags, ','), ',biology,', ',medical-ai,'))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('biology', tags)
   AND NOT FIND_IN_SET('medical-ai', tags);
-- biophysics -> medical-ai
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM
               REPLACE(
                 REPLACE(CONCAT(',', tags, ','), ',biophysics,', ','),
                 ',,', ','))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('biophysics', tags)
   AND FIND_IN_SET('medical-ai', tags);
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM REPLACE(CONCAT(',', tags, ','), ',biophysics,', ',medical-ai,'))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('biophysics', tags)
   AND NOT FIND_IN_SET('medical-ai', tags);
-- biotech -> medical-ai
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM
               REPLACE(
                 REPLACE(CONCAT(',', tags, ','), ',biotech,', ','),
                 ',,', ','))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('biotech', tags)
   AND FIND_IN_SET('medical-ai', tags);
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM REPLACE(CONCAT(',', tags, ','), ',biotech,', ',medical-ai,'))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('biotech', tags)
   AND NOT FIND_IN_SET('medical-ai', tags);
-- brain-computer-interface -> bci
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM
               REPLACE(
                 REPLACE(CONCAT(',', tags, ','), ',brain-computer-interface,', ','),
                 ',,', ','))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('brain-computer-interface', tags)
   AND FIND_IN_SET('bci', tags);
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM REPLACE(CONCAT(',', tags, ','), ',brain-computer-interface,', ',bci,'))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('brain-computer-interface', tags)
   AND NOT FIND_IN_SET('bci', tags);
-- brain-inspired -> neuro-symbolic
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM
               REPLACE(
                 REPLACE(CONCAT(',', tags, ','), ',brain-inspired,', ','),
                 ',,', ','))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('brain-inspired', tags)
   AND FIND_IN_SET('neuro-symbolic', tags);
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM REPLACE(CONCAT(',', tags, ','), ',brain-inspired,', ',neuro-symbolic,'))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('brain-inspired', tags)
   AND NOT FIND_IN_SET('neuro-symbolic', tags);
-- brain-machine-interface -> bci
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM
               REPLACE(
                 REPLACE(CONCAT(',', tags, ','), ',brain-machine-interface,', ','),
                 ',,', ','))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('brain-machine-interface', tags)
   AND FIND_IN_SET('bci', tags);
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM REPLACE(CONCAT(',', tags, ','), ',brain-machine-interface,', ',bci,'))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('brain-machine-interface', tags)
   AND NOT FIND_IN_SET('bci', tags);
-- brain-stimulation -> bci
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM
               REPLACE(
                 REPLACE(CONCAT(',', tags, ','), ',brain-stimulation,', ','),
                 ',,', ','))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('brain-stimulation', tags)
   AND FIND_IN_SET('bci', tags);
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM REPLACE(CONCAT(',', tags, ','), ',brain-stimulation,', ',bci,'))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('brain-stimulation', tags)
   AND NOT FIND_IN_SET('bci', tags);
-- brownian-motion -> physics
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM
               REPLACE(
                 REPLACE(CONCAT(',', tags, ','), ',brownian-motion,', ','),
                 ',,', ','))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('brownian-motion', tags)
   AND FIND_IN_SET('physics', tags);
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM REPLACE(CONCAT(',', tags, ','), ',brownian-motion,', ',physics,'))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('brownian-motion', tags)
   AND NOT FIND_IN_SET('physics', tags);
-- cancer -> medical-ai
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM
               REPLACE(
                 REPLACE(CONCAT(',', tags, ','), ',cancer,', ','),
                 ',,', ','))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('cancer', tags)
   AND FIND_IN_SET('medical-ai', tags);
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM REPLACE(CONCAT(',', tags, ','), ',cancer,', ',medical-ai,'))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('cancer', tags)
   AND NOT FIND_IN_SET('medical-ai', tags);
-- cell-biology -> medical-ai
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM
               REPLACE(
                 REPLACE(CONCAT(',', tags, ','), ',cell-biology,', ','),
                 ',,', ','))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('cell-biology', tags)
   AND FIND_IN_SET('medical-ai', tags);
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM REPLACE(CONCAT(',', tags, ','), ',cell-biology,', ',medical-ai,'))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('cell-biology', tags)
   AND NOT FIND_IN_SET('medical-ai', tags);
-- chain-of-thought -> ai-safety
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM
               REPLACE(
                 REPLACE(CONCAT(',', tags, ','), ',chain-of-thought,', ','),
                 ',,', ','))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('chain-of-thought', tags)
   AND FIND_IN_SET('ai-safety', tags);
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM REPLACE(CONCAT(',', tags, ','), ',chain-of-thought,', ',ai-safety,'))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('chain-of-thought', tags)
   AND NOT FIND_IN_SET('ai-safety', tags);
-- chaos -> physics
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM
               REPLACE(
                 REPLACE(CONCAT(',', tags, ','), ',chaos,', ','),
                 ',,', ','))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('chaos', tags)
   AND FIND_IN_SET('physics', tags);
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM REPLACE(CONCAT(',', tags, ','), ',chaos,', ',physics,'))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('chaos', tags)
   AND NOT FIND_IN_SET('physics', tags);
-- chaos-prediction -> physics
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM
               REPLACE(
                 REPLACE(CONCAT(',', tags, ','), ',chaos-prediction,', ','),
                 ',,', ','))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('chaos-prediction', tags)
   AND FIND_IN_SET('physics', tags);
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM REPLACE(CONCAT(',', tags, ','), ',chaos-prediction,', ',physics,'))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('chaos-prediction', tags)
   AND NOT FIND_IN_SET('physics', tags);
-- circuit-depth -> quantum-computing
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM
               REPLACE(
                 REPLACE(CONCAT(',', tags, ','), ',circuit-depth,', ','),
                 ',,', ','))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('circuit-depth', tags)
   AND FIND_IN_SET('quantum-computing', tags);
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM REPLACE(CONCAT(',', tags, ','), ',circuit-depth,', ',quantum-computing,'))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('circuit-depth', tags)
   AND NOT FIND_IN_SET('quantum-computing', tags);
-- climate -> physics-informed-ml
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM
               REPLACE(
                 REPLACE(CONCAT(',', tags, ','), ',climate,', ','),
                 ',,', ','))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('climate', tags)
   AND FIND_IN_SET('physics-informed-ml', tags);
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM REPLACE(CONCAT(',', tags, ','), ',climate,', ',physics-informed-ml,'))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('climate', tags)
   AND NOT FIND_IN_SET('physics-informed-ml', tags);
-- climate-modeling -> physics-informed-ml
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM
               REPLACE(
                 REPLACE(CONCAT(',', tags, ','), ',climate-modeling,', ','),
                 ',,', ','))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('climate-modeling', tags)
   AND FIND_IN_SET('physics-informed-ml', tags);
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM REPLACE(CONCAT(',', tags, ','), ',climate-modeling,', ',physics-informed-ml,'))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('climate-modeling', tags)
   AND NOT FIND_IN_SET('physics-informed-ml', tags);
-- clinical-trials -> medical-ai
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM
               REPLACE(
                 REPLACE(CONCAT(',', tags, ','), ',clinical-trials,', ','),
                 ',,', ','))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('clinical-trials', tags)
   AND FIND_IN_SET('medical-ai', tags);
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM REPLACE(CONCAT(',', tags, ','), ',clinical-trials,', ',medical-ai,'))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('clinical-trials', tags)
   AND NOT FIND_IN_SET('medical-ai', tags);
-- cognition -> reasoning
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM
               REPLACE(
                 REPLACE(CONCAT(',', tags, ','), ',cognition,', ','),
                 ',,', ','))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('cognition', tags)
   AND FIND_IN_SET('reasoning', tags);
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM REPLACE(CONCAT(',', tags, ','), ',cognition,', ',reasoning,'))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('cognition', tags)
   AND NOT FIND_IN_SET('reasoning', tags);
-- coma -> medical-ai
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM
               REPLACE(
                 REPLACE(CONCAT(',', tags, ','), ',coma,', ','),
                 ',,', ','))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('coma', tags)
   AND FIND_IN_SET('medical-ai', tags);
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM REPLACE(CONCAT(',', tags, ','), ',coma,', ',medical-ai,'))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('coma', tags)
   AND NOT FIND_IN_SET('medical-ai', tags);
-- compiler -> ai-for-math
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM
               REPLACE(
                 REPLACE(CONCAT(',', tags, ','), ',compiler,', ','),
                 ',,', ','))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('compiler', tags)
   AND FIND_IN_SET('ai-for-math', tags);
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM REPLACE(CONCAT(',', tags, ','), ',compiler,', ',ai-for-math,'))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('compiler', tags)
   AND NOT FIND_IN_SET('ai-for-math', tags);
-- computing -> ai
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM
               REPLACE(
                 REPLACE(CONCAT(',', tags, ','), ',computing,', ','),
                 ',,', ','))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('computing', tags)
   AND FIND_IN_SET('ai', tags);
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM REPLACE(CONCAT(',', tags, ','), ',computing,', ',ai,'))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('computing', tags)
   AND NOT FIND_IN_SET('ai', tags);
-- condensed-matter -> physics
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM
               REPLACE(
                 REPLACE(CONCAT(',', tags, ','), ',condensed-matter,', ','),
                 ',,', ','))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('condensed-matter', tags)
   AND FIND_IN_SET('physics', tags);
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM REPLACE(CONCAT(',', tags, ','), ',condensed-matter,', ',physics,'))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('condensed-matter', tags)
   AND NOT FIND_IN_SET('physics', tags);
-- control-theory -> reasoning
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM
               REPLACE(
                 REPLACE(CONCAT(',', tags, ','), ',control-theory,', ','),
                 ',,', ','))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('control-theory', tags)
   AND FIND_IN_SET('reasoning', tags);
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM REPLACE(CONCAT(',', tags, ','), ',control-theory,', ',reasoning,'))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('control-theory', tags)
   AND NOT FIND_IN_SET('reasoning', tags);
-- data-storage -> genomics
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM
               REPLACE(
                 REPLACE(CONCAT(',', tags, ','), ',data-storage,', ','),
                 ',,', ','))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('data-storage', tags)
   AND FIND_IN_SET('genomics', tags);
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM REPLACE(CONCAT(',', tags, ','), ',data-storage,', ',genomics,'))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('data-storage', tags)
   AND NOT FIND_IN_SET('genomics', tags);
-- democratization -> energy
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM
               REPLACE(
                 REPLACE(CONCAT(',', tags, ','), ',democratization,', ','),
                 ',,', ','))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('democratization', tags)
   AND FIND_IN_SET('energy', tags);
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM REPLACE(CONCAT(',', tags, ','), ',democratization,', ',energy,'))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('democratization', tags)
   AND NOT FIND_IN_SET('energy', tags);
-- dielectric -> physics
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM
               REPLACE(
                 REPLACE(CONCAT(',', tags, ','), ',dielectric,', ','),
                 ',,', ','))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('dielectric', tags)
   AND FIND_IN_SET('physics', tags);
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM REPLACE(CONCAT(',', tags, ','), ',dielectric,', ',physics,'))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('dielectric', tags)
   AND NOT FIND_IN_SET('physics', tags);
-- diffusion-model -> generative-models
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM
               REPLACE(
                 REPLACE(CONCAT(',', tags, ','), ',diffusion-model,', ','),
                 ',,', ','))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('diffusion-model', tags)
   AND FIND_IN_SET('generative-models', tags);
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM REPLACE(CONCAT(',', tags, ','), ',diffusion-model,', ',generative-models,'))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('diffusion-model', tags)
   AND NOT FIND_IN_SET('generative-models', tags);
-- diffusion-models -> generative-models
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM
               REPLACE(
                 REPLACE(CONCAT(',', tags, ','), ',diffusion-models,', ','),
                 ',,', ','))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('diffusion-models', tags)
   AND FIND_IN_SET('generative-models', tags);
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM REPLACE(CONCAT(',', tags, ','), ',diffusion-models,', ',generative-models,'))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('diffusion-models', tags)
   AND NOT FIND_IN_SET('generative-models', tags);
-- dna -> genomics
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM
               REPLACE(
                 REPLACE(CONCAT(',', tags, ','), ',dna,', ','),
                 ',,', ','))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('dna', tags)
   AND FIND_IN_SET('genomics', tags);
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM REPLACE(CONCAT(',', tags, ','), ',dna,', ',genomics,'))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('dna', tags)
   AND NOT FIND_IN_SET('genomics', tags);
-- dna-robots -> molecular-computing
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM
               REPLACE(
                 REPLACE(CONCAT(',', tags, ','), ',dna-robots,', ','),
                 ',,', ','))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('dna-robots', tags)
   AND FIND_IN_SET('molecular-computing', tags);
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM REPLACE(CONCAT(',', tags, ','), ',dna-robots,', ',molecular-computing,'))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('dna-robots', tags)
   AND NOT FIND_IN_SET('molecular-computing', tags);
-- dna-storage -> genomics
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM
               REPLACE(
                 REPLACE(CONCAT(',', tags, ','), ',dna-storage,', ','),
                 ',,', ','))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('dna-storage', tags)
   AND FIND_IN_SET('genomics', tags);
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM REPLACE(CONCAT(',', tags, ','), ',dna-storage,', ',genomics,'))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('dna-storage', tags)
   AND NOT FIND_IN_SET('genomics', tags);
-- drug-delivery -> medical-ai
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM
               REPLACE(
                 REPLACE(CONCAT(',', tags, ','), ',drug-delivery,', ','),
                 ',,', ','))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('drug-delivery', tags)
   AND FIND_IN_SET('medical-ai', tags);
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM REPLACE(CONCAT(',', tags, ','), ',drug-delivery,', ',medical-ai,'))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('drug-delivery', tags)
   AND NOT FIND_IN_SET('medical-ai', tags);
-- drug-discovery -> medical-ai
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM
               REPLACE(
                 REPLACE(CONCAT(',', tags, ','), ',drug-discovery,', ','),
                 ',,', ','))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('drug-discovery', tags)
   AND FIND_IN_SET('medical-ai', tags);
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM REPLACE(CONCAT(',', tags, ','), ',drug-discovery,', ',medical-ai,'))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('drug-discovery', tags)
   AND NOT FIND_IN_SET('medical-ai', tags);
-- dusty-plasma -> physics
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM
               REPLACE(
                 REPLACE(CONCAT(',', tags, ','), ',dusty-plasma,', ','),
                 ',,', ','))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('dusty-plasma', tags)
   AND FIND_IN_SET('physics', tags);
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM REPLACE(CONCAT(',', tags, ','), ',dusty-plasma,', ',physics,'))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('dusty-plasma', tags)
   AND NOT FIND_IN_SET('physics', tags);
-- energy-efficiency -> energy
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM
               REPLACE(
                 REPLACE(CONCAT(',', tags, ','), ',energy-efficiency,', ','),
                 ',,', ','))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('energy-efficiency', tags)
   AND FIND_IN_SET('energy', tags);
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM REPLACE(CONCAT(',', tags, ','), ',energy-efficiency,', ',energy,'))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('energy-efficiency', tags)
   AND NOT FIND_IN_SET('energy', tags);
-- epigenetics -> genomics
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM
               REPLACE(
                 REPLACE(CONCAT(',', tags, ','), ',epigenetics,', ','),
                 ',,', ','))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('epigenetics', tags)
   AND FIND_IN_SET('genomics', tags);
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM REPLACE(CONCAT(',', tags, ','), ',epigenetics,', ',genomics,'))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('epigenetics', tags)
   AND NOT FIND_IN_SET('genomics', tags);
-- ev -> physics
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM
               REPLACE(
                 REPLACE(CONCAT(',', tags, ','), ',ev,', ','),
                 ',,', ','))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('ev', tags)
   AND FIND_IN_SET('physics', tags);
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM REPLACE(CONCAT(',', tags, ','), ',ev,', ',physics,'))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('ev', tags)
   AND NOT FIND_IN_SET('physics', tags);
-- evaluation -> ai-evaluation
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM
               REPLACE(
                 REPLACE(CONCAT(',', tags, ','), ',evaluation,', ','),
                 ',,', ','))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('evaluation', tags)
   AND FIND_IN_SET('ai-evaluation', tags);
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM REPLACE(CONCAT(',', tags, ','), ',evaluation,', ',ai-evaluation,'))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('evaluation', tags)
   AND NOT FIND_IN_SET('ai-evaluation', tags);
-- evolutionary-ai -> ai-for-math
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM
               REPLACE(
                 REPLACE(CONCAT(',', tags, ','), ',evolutionary-ai,', ','),
                 ',,', ','))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('evolutionary-ai', tags)
   AND FIND_IN_SET('ai-for-math', tags);
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM REPLACE(CONCAT(',', tags, ','), ',evolutionary-ai,', ',ai-for-math,'))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('evolutionary-ai', tags)
   AND NOT FIND_IN_SET('ai-for-math', tags);
-- exoplanets -> space
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM
               REPLACE(
                 REPLACE(CONCAT(',', tags, ','), ',exoplanets,', ','),
                 ',,', ','))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('exoplanets', tags)
   AND FIND_IN_SET('space', tags);
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM REPLACE(CONCAT(',', tags, ','), ',exoplanets,', ',space,'))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('exoplanets', tags)
   AND NOT FIND_IN_SET('space', tags);
-- extreme-computing -> energy
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM
               REPLACE(
                 REPLACE(CONCAT(',', tags, ','), ',extreme-computing,', ','),
                 ',,', ','))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('extreme-computing', tags)
   AND FIND_IN_SET('energy', tags);
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM REPLACE(CONCAT(',', tags, ','), ',extreme-computing,', ',energy,'))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('extreme-computing', tags)
   AND NOT FIND_IN_SET('energy', tags);
-- fungal-computing -> biocomputing
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM
               REPLACE(
                 REPLACE(CONCAT(',', tags, ','), ',fungal-computing,', ','),
                 ',,', ','))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('fungal-computing', tags)
   AND FIND_IN_SET('biocomputing', tags);
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM REPLACE(CONCAT(',', tags, ','), ',fungal-computing,', ',biocomputing,'))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('fungal-computing', tags)
   AND NOT FIND_IN_SET('biocomputing', tags);
-- generative-ai -> generative-models
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM
               REPLACE(
                 REPLACE(CONCAT(',', tags, ','), ',generative-ai,', ','),
                 ',,', ','))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('generative-ai', tags)
   AND FIND_IN_SET('generative-models', tags);
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM REPLACE(CONCAT(',', tags, ','), ',generative-ai,', ',generative-models,'))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('generative-ai', tags)
   AND NOT FIND_IN_SET('generative-models', tags);
-- genetic-circuits -> synthetic-biology
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM
               REPLACE(
                 REPLACE(CONCAT(',', tags, ','), ',genetic-circuits,', ','),
                 ',,', ','))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('genetic-circuits', tags)
   AND FIND_IN_SET('synthetic-biology', tags);
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM REPLACE(CONCAT(',', tags, ','), ',genetic-circuits,', ',synthetic-biology,'))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('genetic-circuits', tags)
   AND NOT FIND_IN_SET('synthetic-biology', tags);
-- godel -> ai-for-math
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM
               REPLACE(
                 REPLACE(CONCAT(',', tags, ','), ',godel,', ','),
                 ',,', ','))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('godel', tags)
   AND FIND_IN_SET('ai-for-math', tags);
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM REPLACE(CONCAT(',', tags, ','), ',godel,', ',ai-for-math,'))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('godel', tags)
   AND NOT FIND_IN_SET('ai-for-math', tags);
-- goedel -> ai-for-math
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM
               REPLACE(
                 REPLACE(CONCAT(',', tags, ','), ',goedel,', ','),
                 ',,', ','))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('goedel', tags)
   AND FIND_IN_SET('ai-for-math', tags);
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM REPLACE(CONCAT(',', tags, ','), ',goedel,', ',ai-for-math,'))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('goedel', tags)
   AND NOT FIND_IN_SET('ai-for-math', tags);
-- goodfire -> mechanistic-interpretability
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM
               REPLACE(
                 REPLACE(CONCAT(',', tags, ','), ',goodfire,', ','),
                 ',,', ','))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('goodfire', tags)
   AND FIND_IN_SET('mechanistic-interpretability', tags);
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM REPLACE(CONCAT(',', tags, ','), ',goodfire,', ',mechanistic-interpretability,'))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('goodfire', tags)
   AND NOT FIND_IN_SET('mechanistic-interpretability', tags);
-- graph-neural-network -> generative-models
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM
               REPLACE(
                 REPLACE(CONCAT(',', tags, ','), ',graph-neural-network,', ','),
                 ',,', ','))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('graph-neural-network', tags)
   AND FIND_IN_SET('generative-models', tags);
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM REPLACE(CONCAT(',', tags, ','), ',graph-neural-network,', ',generative-models,'))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('graph-neural-network', tags)
   AND NOT FIND_IN_SET('generative-models', tags);
-- graphene -> materials-science
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM
               REPLACE(
                 REPLACE(CONCAT(',', tags, ','), ',graphene,', ','),
                 ',,', ','))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('graphene', tags)
   AND FIND_IN_SET('materials-science', tags);
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM REPLACE(CONCAT(',', tags, ','), ',graphene,', ',materials-science,'))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('graphene', tags)
   AND NOT FIND_IN_SET('materials-science', tags);
-- hardware -> neuromorphic
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM
               REPLACE(
                 REPLACE(CONCAT(',', tags, ','), ',hardware,', ','),
                 ',,', ','))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('hardware', tags)
   AND FIND_IN_SET('neuromorphic', tags);
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM REPLACE(CONCAT(',', tags, ','), ',hardware,', ',neuromorphic,'))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('hardware', tags)
   AND NOT FIND_IN_SET('neuromorphic', tags);
-- health -> medical-ai
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM
               REPLACE(
                 REPLACE(CONCAT(',', tags, ','), ',health,', ','),
                 ',,', ','))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('health', tags)
   AND FIND_IN_SET('medical-ai', tags);
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM REPLACE(CONCAT(',', tags, ','), ',health,', ',medical-ai,'))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('health', tags)
   AND NOT FIND_IN_SET('medical-ai', tags);
-- hybrid -> neuro-symbolic
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM
               REPLACE(
                 REPLACE(CONCAT(',', tags, ','), ',hybrid,', ','),
                 ',,', ','))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('hybrid', tags)
   AND FIND_IN_SET('neuro-symbolic', tags);
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM REPLACE(CONCAT(',', tags, ','), ',hybrid,', ',neuro-symbolic,'))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('hybrid', tags)
   AND NOT FIND_IN_SET('neuro-symbolic', tags);
-- iit -> consciousness
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM
               REPLACE(
                 REPLACE(CONCAT(',', tags, ','), ',iit,', ','),
                 ',,', ','))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('iit', tags)
   AND FIND_IN_SET('consciousness', tags);
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM REPLACE(CONCAT(',', tags, ','), ',iit,', ',consciousness,'))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('iit', tags)
   AND NOT FIND_IN_SET('consciousness', tags);
-- inner-speech -> reasoning
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM
               REPLACE(
                 REPLACE(CONCAT(',', tags, ','), ',inner-speech,', ','),
                 ',,', ','))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('inner-speech', tags)
   AND FIND_IN_SET('reasoning', tags);
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM REPLACE(CONCAT(',', tags, ','), ',inner-speech,', ',reasoning,'))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('inner-speech', tags)
   AND NOT FIND_IN_SET('reasoning', tags);
-- insilico-medicine -> medical-ai
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM
               REPLACE(
                 REPLACE(CONCAT(',', tags, ','), ',insilico-medicine,', ','),
                 ',,', ','))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('insilico-medicine', tags)
   AND FIND_IN_SET('medical-ai', tags);
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM REPLACE(CONCAT(',', tags, ','), ',insilico-medicine,', ',medical-ai,'))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('insilico-medicine', tags)
   AND NOT FIND_IN_SET('medical-ai', tags);
-- interpretability -> mechanistic-interpretability
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM
               REPLACE(
                 REPLACE(CONCAT(',', tags, ','), ',interpretability,', ','),
                 ',,', ','))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('interpretability', tags)
   AND FIND_IN_SET('mechanistic-interpretability', tags);
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM REPLACE(CONCAT(',', tags, ','), ',interpretability,', ',mechanistic-interpretability,'))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('interpretability', tags)
   AND NOT FIND_IN_SET('mechanistic-interpretability', tags);
-- isomorphic-labs -> proteins
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM
               REPLACE(
                 REPLACE(CONCAT(',', tags, ','), ',isomorphic-labs,', ','),
                 ',,', ','))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('isomorphic-labs', tags)
   AND FIND_IN_SET('proteins', tags);
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM REPLACE(CONCAT(',', tags, ','), ',isomorphic-labs,', ',proteins,'))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('isomorphic-labs', tags)
   AND NOT FIND_IN_SET('proteins', tags);
-- jevons-paradox -> energy
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM
               REPLACE(
                 REPLACE(CONCAT(',', tags, ','), ',jevons-paradox,', ','),
                 ',,', ','))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('jevons-paradox', tags)
   AND FIND_IN_SET('energy', tags);
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM REPLACE(CONCAT(',', tags, ','), ',jevons-paradox,', ',energy,'))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('jevons-paradox', tags)
   AND NOT FIND_IN_SET('energy', tags);
-- kv-cache -> llm
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM
               REPLACE(
                 REPLACE(CONCAT(',', tags, ','), ',kv-cache,', ','),
                 ',,', ','))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('kv-cache', tags)
   AND FIND_IN_SET('llm', tags);
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM REPLACE(CONCAT(',', tags, ','), ',kv-cache,', ',llm,'))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('kv-cache', tags)
   AND NOT FIND_IN_SET('llm', tags);
-- lip-sync -> generative-models
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM
               REPLACE(
                 REPLACE(CONCAT(',', tags, ','), ',lip-sync,', ','),
                 ',,', ','))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('lip-sync', tags)
   AND FIND_IN_SET('generative-models', tags);
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM REPLACE(CONCAT(',', tags, ','), ',lip-sync,', ',generative-models,'))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('lip-sync', tags)
   AND NOT FIND_IN_SET('generative-models', tags);
-- llms -> llm
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM
               REPLACE(
                 REPLACE(CONCAT(',', tags, ','), ',llms,', ','),
                 ',,', ','))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('llms', tags)
   AND FIND_IN_SET('llm', tags);
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM REPLACE(CONCAT(',', tags, ','), ',llms,', ',llm,'))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('llms', tags)
   AND NOT FIND_IN_SET('llm', tags);
-- longevity -> medical-ai
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM
               REPLACE(
                 REPLACE(CONCAT(',', tags, ','), ',longevity,', ','),
                 ',,', ','))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('longevity', tags)
   AND FIND_IN_SET('medical-ai', tags);
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM REPLACE(CONCAT(',', tags, ','), ',longevity,', ',medical-ai,'))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('longevity', tags)
   AND NOT FIND_IN_SET('medical-ai', tags);
-- lucid-dreaming -> bci
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM
               REPLACE(
                 REPLACE(CONCAT(',', tags, ','), ',lucid-dreaming,', ','),
                 ',,', ','))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('lucid-dreaming', tags)
   AND FIND_IN_SET('bci', tags);
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM REPLACE(CONCAT(',', tags, ','), ',lucid-dreaming,', ',bci,'))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('lucid-dreaming', tags)
   AND NOT FIND_IN_SET('bci', tags);
-- machine-learning -> ai
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM
               REPLACE(
                 REPLACE(CONCAT(',', tags, ','), ',machine-learning,', ','),
                 ',,', ','))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('machine-learning', tags)
   AND FIND_IN_SET('ai', tags);
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM REPLACE(CONCAT(',', tags, ','), ',machine-learning,', ',ai,'))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('machine-learning', tags)
   AND NOT FIND_IN_SET('ai', tags);
-- magnets -> physics
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM
               REPLACE(
                 REPLACE(CONCAT(',', tags, ','), ',magnets,', ','),
                 ',,', ','))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('magnets', tags)
   AND FIND_IN_SET('physics', tags);
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM REPLACE(CONCAT(',', tags, ','), ',magnets,', ',physics,'))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('magnets', tags)
   AND NOT FIND_IN_SET('physics', tags);
-- materials -> materials-science
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM
               REPLACE(
                 REPLACE(CONCAT(',', tags, ','), ',materials,', ','),
                 ',,', ','))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('materials', tags)
   AND FIND_IN_SET('materials-science', tags);
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM REPLACE(CONCAT(',', tags, ','), ',materials,', ',materials-science,'))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('materials', tags)
   AND NOT FIND_IN_SET('materials-science', tags);
-- math -> ai-for-math
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM
               REPLACE(
                 REPLACE(CONCAT(',', tags, ','), ',math,', ','),
                 ',,', ','))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('math', tags)
   AND FIND_IN_SET('ai-for-math', tags);
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM REPLACE(CONCAT(',', tags, ','), ',math,', ',ai-for-math,'))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('math', tags)
   AND NOT FIND_IN_SET('ai-for-math', tags);
-- mathematical-creativity -> ai-for-math
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM
               REPLACE(
                 REPLACE(CONCAT(',', tags, ','), ',mathematical-creativity,', ','),
                 ',,', ','))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('mathematical-creativity', tags)
   AND FIND_IN_SET('ai-for-math', tags);
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM REPLACE(CONCAT(',', tags, ','), ',mathematical-creativity,', ',ai-for-math,'))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('mathematical-creativity', tags)
   AND NOT FIND_IN_SET('ai-for-math', tags);
-- mathematics -> ai-for-math
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM
               REPLACE(
                 REPLACE(CONCAT(',', tags, ','), ',mathematics,', ','),
                 ',,', ','))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('mathematics', tags)
   AND FIND_IN_SET('ai-for-math', tags);
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM REPLACE(CONCAT(',', tags, ','), ',mathematics,', ',ai-for-math,'))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('mathematics', tags)
   AND NOT FIND_IN_SET('ai-for-math', tags);
-- memory -> memory-systems
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM
               REPLACE(
                 REPLACE(CONCAT(',', tags, ','), ',memory,', ','),
                 ',,', ','))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('memory', tags)
   AND FIND_IN_SET('memory-systems', tags);
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM REPLACE(CONCAT(',', tags, ','), ',memory,', ',memory-systems,'))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('memory', tags)
   AND NOT FIND_IN_SET('memory-systems', tags);
-- memory-chip -> memory-systems
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM
               REPLACE(
                 REPLACE(CONCAT(',', tags, ','), ',memory-chip,', ','),
                 ',,', ','))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('memory-chip', tags)
   AND FIND_IN_SET('memory-systems', tags);
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM REPLACE(CONCAT(',', tags, ','), ',memory-chip,', ',memory-systems,'))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('memory-chip', tags)
   AND NOT FIND_IN_SET('memory-systems', tags);
-- memory-compute -> memory-systems
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM
               REPLACE(
                 REPLACE(CONCAT(',', tags, ','), ',memory-compute,', ','),
                 ',,', ','))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('memory-compute', tags)
   AND FIND_IN_SET('memory-systems', tags);
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM REPLACE(CONCAT(',', tags, ','), ',memory-compute,', ',memory-systems,'))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('memory-compute', tags)
   AND NOT FIND_IN_SET('memory-systems', tags);
-- memristor -> neuromorphic
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM
               REPLACE(
                 REPLACE(CONCAT(',', tags, ','), ',memristor,', ','),
                 ',,', ','))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('memristor', tags)
   AND FIND_IN_SET('neuromorphic', tags);
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM REPLACE(CONCAT(',', tags, ','), ',memristor,', ',neuromorphic,'))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('memristor', tags)
   AND NOT FIND_IN_SET('neuromorphic', tags);
-- ml -> ai
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM
               REPLACE(
                 REPLACE(CONCAT(',', tags, ','), ',ml,', ','),
                 ',,', ','))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('ml', tags)
   AND FIND_IN_SET('ai', tags);
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM REPLACE(CONCAT(',', tags, ','), ',ml,', ',ai,'))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('ml', tags)
   AND NOT FIND_IN_SET('ai', tags);
-- multitasking -> reasoning
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM
               REPLACE(
                 REPLACE(CONCAT(',', tags, ','), ',multitasking,', ','),
                 ',,', ','))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('multitasking', tags)
   AND FIND_IN_SET('reasoning', tags);
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM REPLACE(CONCAT(',', tags, ','), ',multitasking,', ',reasoning,'))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('multitasking', tags)
   AND NOT FIND_IN_SET('reasoning', tags);
-- mycelium -> biocomputing
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM
               REPLACE(
                 REPLACE(CONCAT(',', tags, ','), ',mycelium,', ','),
                 ',,', ','))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('mycelium', tags)
   AND FIND_IN_SET('biocomputing', tags);
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM REPLACE(CONCAT(',', tags, ','), ',mycelium,', ',biocomputing,'))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('mycelium', tags)
   AND NOT FIND_IN_SET('biocomputing', tags);
-- nanoengineering -> materials-science
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM
               REPLACE(
                 REPLACE(CONCAT(',', tags, ','), ',nanoengineering,', ','),
                 ',,', ','))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('nanoengineering', tags)
   AND FIND_IN_SET('materials-science', tags);
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM REPLACE(CONCAT(',', tags, ','), ',nanoengineering,', ',materials-science,'))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('nanoengineering', tags)
   AND NOT FIND_IN_SET('materials-science', tags);
-- nanotechnology -> materials-science
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM
               REPLACE(
                 REPLACE(CONCAT(',', tags, ','), ',nanotechnology,', ','),
                 ',,', ','))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('nanotechnology', tags)
   AND FIND_IN_SET('materials-science', tags);
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM REPLACE(CONCAT(',', tags, ','), ',nanotechnology,', ',materials-science,'))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('nanotechnology', tags)
   AND NOT FIND_IN_SET('materials-science', tags);
-- nde -> consciousness
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM
               REPLACE(
                 REPLACE(CONCAT(',', tags, ','), ',nde,', ','),
                 ',,', ','))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('nde', tags)
   AND FIND_IN_SET('consciousness', tags);
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM REPLACE(CONCAT(',', tags, ','), ',nde,', ',consciousness,'))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('nde', tags)
   AND NOT FIND_IN_SET('consciousness', tags);
-- near-death-experience -> consciousness
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM
               REPLACE(
                 REPLACE(CONCAT(',', tags, ','), ',near-death-experience,', ','),
                 ',,', ','))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('near-death-experience', tags)
   AND FIND_IN_SET('consciousness', tags);
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM REPLACE(CONCAT(',', tags, ','), ',near-death-experience,', ',consciousness,'))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('near-death-experience', tags)
   AND NOT FIND_IN_SET('consciousness', tags);
-- neural-network -> ai
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM
               REPLACE(
                 REPLACE(CONCAT(',', tags, ','), ',neural-network,', ','),
                 ',,', ','))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('neural-network', tags)
   AND FIND_IN_SET('ai', tags);
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM REPLACE(CONCAT(',', tags, ','), ',neural-network,', ',ai,'))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('neural-network', tags)
   AND NOT FIND_IN_SET('ai', tags);
-- neural-networks -> ai
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM
               REPLACE(
                 REPLACE(CONCAT(',', tags, ','), ',neural-networks,', ','),
                 ',,', ','))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('neural-networks', tags)
   AND FIND_IN_SET('ai', tags);
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM REPLACE(CONCAT(',', tags, ','), ',neural-networks,', ',ai,'))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('neural-networks', tags)
   AND NOT FIND_IN_SET('ai', tags);
-- neuro-symbolic-ai -> neuro-symbolic
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM
               REPLACE(
                 REPLACE(CONCAT(',', tags, ','), ',neuro-symbolic-ai,', ','),
                 ',,', ','))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('neuro-symbolic-ai', tags)
   AND FIND_IN_SET('neuro-symbolic', tags);
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM REPLACE(CONCAT(',', tags, ','), ',neuro-symbolic-ai,', ',neuro-symbolic,'))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('neuro-symbolic-ai', tags)
   AND NOT FIND_IN_SET('neuro-symbolic', tags);
-- neurology -> medical-ai
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM
               REPLACE(
                 REPLACE(CONCAT(',', tags, ','), ',neurology,', ','),
                 ',,', ','))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('neurology', tags)
   AND FIND_IN_SET('medical-ai', tags);
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM REPLACE(CONCAT(',', tags, ','), ',neurology,', ',medical-ai,'))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('neurology', tags)
   AND NOT FIND_IN_SET('medical-ai', tags);
-- neurons -> biocomputing
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM
               REPLACE(
                 REPLACE(CONCAT(',', tags, ','), ',neurons,', ','),
                 ',,', ','))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('neurons', tags)
   AND FIND_IN_SET('biocomputing', tags);
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM REPLACE(CONCAT(',', tags, ','), ',neurons,', ',biocomputing,'))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('neurons', tags)
   AND NOT FIND_IN_SET('biocomputing', tags);
-- neuroprosthetics -> bci
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM
               REPLACE(
                 REPLACE(CONCAT(',', tags, ','), ',neuroprosthetics,', ','),
                 ',,', ','))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('neuroprosthetics', tags)
   AND FIND_IN_SET('bci', tags);
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM REPLACE(CONCAT(',', tags, ','), ',neuroprosthetics,', ',bci,'))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('neuroprosthetics', tags)
   AND NOT FIND_IN_SET('bci', tags);
-- neurostimulation -> bci
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM
               REPLACE(
                 REPLACE(CONCAT(',', tags, ','), ',neurostimulation,', ','),
                 ',,', ','))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('neurostimulation', tags)
   AND FIND_IN_SET('bci', tags);
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM REPLACE(CONCAT(',', tags, ','), ',neurostimulation,', ',bci,'))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('neurostimulation', tags)
   AND NOT FIND_IN_SET('bci', tags);
-- nisq -> quantum-computing
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM
               REPLACE(
                 REPLACE(CONCAT(',', tags, ','), ',nisq,', ','),
                 ',,', ','))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('nisq', tags)
   AND FIND_IN_SET('quantum-computing', tags);
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM REPLACE(CONCAT(',', tags, ','), ',nisq,', ',quantum-computing,'))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('nisq', tags)
   AND NOT FIND_IN_SET('quantum-computing', tags);
-- noise -> quantum-computing
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM
               REPLACE(
                 REPLACE(CONCAT(',', tags, ','), ',noise,', ','),
                 ',,', ','))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('noise', tags)
   AND FIND_IN_SET('quantum-computing', tags);
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM REPLACE(CONCAT(',', tags, ','), ',noise,', ',quantum-computing,'))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('noise', tags)
   AND NOT FIND_IN_SET('quantum-computing', tags);
-- openai -> gpt
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM
               REPLACE(
                 REPLACE(CONCAT(',', tags, ','), ',openai,', ','),
                 ',,', ','))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('openai', tags)
   AND FIND_IN_SET('gpt', tags);
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM REPLACE(CONCAT(',', tags, ','), ',openai,', ',gpt,'))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('openai', tags)
   AND NOT FIND_IN_SET('gpt', tags);
-- openevolve -> ai-for-math
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM
               REPLACE(
                 REPLACE(CONCAT(',', tags, ','), ',openevolve,', ','),
                 ',,', ','))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('openevolve', tags)
   AND FIND_IN_SET('ai-for-math', tags);
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM REPLACE(CONCAT(',', tags, ','), ',openevolve,', ',ai-for-math,'))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('openevolve', tags)
   AND NOT FIND_IN_SET('ai-for-math', tags);
-- optics -> physics
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM
               REPLACE(
                 REPLACE(CONCAT(',', tags, ','), ',optics,', ','),
                 ',,', ','))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('optics', tags)
   AND FIND_IN_SET('physics', tags);
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM REPLACE(CONCAT(',', tags, ','), ',optics,', ',physics,'))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('optics', tags)
   AND NOT FIND_IN_SET('physics', tags);
-- optimization -> ai-for-math
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM
               REPLACE(
                 REPLACE(CONCAT(',', tags, ','), ',optimization,', ','),
                 ',,', ','))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('optimization', tags)
   AND FIND_IN_SET('ai-for-math', tags);
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM REPLACE(CONCAT(',', tags, ','), ',optimization,', ',ai-for-math,'))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('optimization', tags)
   AND NOT FIND_IN_SET('ai-for-math', tags);
-- organoids -> biocomputing
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM
               REPLACE(
                 REPLACE(CONCAT(',', tags, ','), ',organoids,', ','),
                 ',,', ','))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('organoids', tags)
   AND FIND_IN_SET('biocomputing', tags);
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM REPLACE(CONCAT(',', tags, ','), ',organoids,', ',biocomputing,'))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('organoids', tags)
   AND NOT FIND_IN_SET('biocomputing', tags);
-- panpsychism -> consciousness
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM
               REPLACE(
                 REPLACE(CONCAT(',', tags, ','), ',panpsychism,', ','),
                 ',,', ','))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('panpsychism', tags)
   AND FIND_IN_SET('consciousness', tags);
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM REPLACE(CONCAT(',', tags, ','), ',panpsychism,', ',consciousness,'))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('panpsychism', tags)
   AND NOT FIND_IN_SET('consciousness', tags);
-- panspermia -> space
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM
               REPLACE(
                 REPLACE(CONCAT(',', tags, ','), ',panspermia,', ','),
                 ',,', ','))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('panspermia', tags)
   AND FIND_IN_SET('space', tags);
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM REPLACE(CONCAT(',', tags, ','), ',panspermia,', ',space,'))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('panspermia', tags)
   AND NOT FIND_IN_SET('space', tags);
-- particle-accelerator -> physics
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM
               REPLACE(
                 REPLACE(CONCAT(',', tags, ','), ',particle-accelerator,', ','),
                 ',,', ','))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('particle-accelerator', tags)
   AND FIND_IN_SET('physics', tags);
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM REPLACE(CONCAT(',', tags, ','), ',particle-accelerator,', ',physics,'))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('particle-accelerator', tags)
   AND NOT FIND_IN_SET('physics', tags);
-- pattern-matching -> reasoning
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM
               REPLACE(
                 REPLACE(CONCAT(',', tags, ','), ',pattern-matching,', ','),
                 ',,', ','))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('pattern-matching', tags)
   AND FIND_IN_SET('reasoning', tags);
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM REPLACE(CONCAT(',', tags, ','), ',pattern-matching,', ',reasoning,'))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('pattern-matching', tags)
   AND NOT FIND_IN_SET('reasoning', tags);
-- pde -> physics-informed-ml
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM
               REPLACE(
                 REPLACE(CONCAT(',', tags, ','), ',pde,', ','),
                 ',,', ','))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('pde', tags)
   AND FIND_IN_SET('physics-informed-ml', tags);
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM REPLACE(CONCAT(',', tags, ','), ',pde,', ',physics-informed-ml,'))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('pde', tags)
   AND NOT FIND_IN_SET('physics-informed-ml', tags);
-- peer-review -> ai-evaluation
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM
               REPLACE(
                 REPLACE(CONCAT(',', tags, ','), ',peer-review,', ','),
                 ',,', ','))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('peer-review', tags)
   AND FIND_IN_SET('ai-evaluation', tags);
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM REPLACE(CONCAT(',', tags, ','), ',peer-review,', ',ai-evaluation,'))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('peer-review', tags)
   AND NOT FIND_IN_SET('ai-evaluation', tags);
-- philosophy -> consciousness
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM
               REPLACE(
                 REPLACE(CONCAT(',', tags, ','), ',philosophy,', ','),
                 ',,', ','))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('philosophy', tags)
   AND FIND_IN_SET('consciousness', tags);
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM REPLACE(CONCAT(',', tags, ','), ',philosophy,', ',consciousness,'))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('philosophy', tags)
   AND NOT FIND_IN_SET('consciousness', tags);
-- philosophy-of-mind -> consciousness
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM
               REPLACE(
                 REPLACE(CONCAT(',', tags, ','), ',philosophy-of-mind,', ','),
                 ',,', ','))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('philosophy-of-mind', tags)
   AND FIND_IN_SET('consciousness', tags);
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM REPLACE(CONCAT(',', tags, ','), ',philosophy-of-mind,', ',consciousness,'))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('philosophy-of-mind', tags)
   AND NOT FIND_IN_SET('consciousness', tags);
-- photonic-computing -> neuromorphic
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM
               REPLACE(
                 REPLACE(CONCAT(',', tags, ','), ',photonic-computing,', ','),
                 ',,', ','))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('photonic-computing', tags)
   AND FIND_IN_SET('neuromorphic', tags);
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM REPLACE(CONCAT(',', tags, ','), ',photonic-computing,', ',neuromorphic,'))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('photonic-computing', tags)
   AND NOT FIND_IN_SET('neuromorphic', tags);
-- photosynthesis -> quantum-biology
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM
               REPLACE(
                 REPLACE(CONCAT(',', tags, ','), ',photosynthesis,', ','),
                 ',,', ','))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('photosynthesis', tags)
   AND FIND_IN_SET('quantum-biology', tags);
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM REPLACE(CONCAT(',', tags, ','), ',photosynthesis,', ',quantum-biology,'))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('photosynthesis', tags)
   AND NOT FIND_IN_SET('quantum-biology', tags);
-- physics-informed -> physics-informed-ml
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM
               REPLACE(
                 REPLACE(CONCAT(',', tags, ','), ',physics-informed,', ','),
                 ',,', ','))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('physics-informed', tags)
   AND FIND_IN_SET('physics-informed-ml', tags);
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM REPLACE(CONCAT(',', tags, ','), ',physics-informed,', ',physics-informed-ml,'))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('physics-informed', tags)
   AND NOT FIND_IN_SET('physics-informed-ml', tags);
-- planning -> reasoning
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM
               REPLACE(
                 REPLACE(CONCAT(',', tags, ','), ',planning,', ','),
                 ',,', ','))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('planning', tags)
   AND FIND_IN_SET('reasoning', tags);
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM REPLACE(CONCAT(',', tags, ','), ',planning,', ',reasoning,'))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('planning', tags)
   AND NOT FIND_IN_SET('reasoning', tags);
-- plasma -> physics
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM
               REPLACE(
                 REPLACE(CONCAT(',', tags, ','), ',plasma,', ','),
                 ',,', ','))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('plasma', tags)
   AND FIND_IN_SET('physics', tags);
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM REPLACE(CONCAT(',', tags, ','), ',plasma,', ',physics,'))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('plasma', tags)
   AND NOT FIND_IN_SET('physics', tags);
-- polymers -> materials-science
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM
               REPLACE(
                 REPLACE(CONCAT(',', tags, ','), ',polymers,', ','),
                 ',,', ','))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('polymers', tags)
   AND FIND_IN_SET('materials-science', tags);
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM REPLACE(CONCAT(',', tags, ','), ',polymers,', ',materials-science,'))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('polymers', tags)
   AND NOT FIND_IN_SET('materials-science', tags);
-- programming-languages -> ai-for-math
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM
               REPLACE(
                 REPLACE(CONCAT(',', tags, ','), ',programming-languages,', ','),
                 ',,', ','))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('programming-languages', tags)
   AND FIND_IN_SET('ai-for-math', tags);
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM REPLACE(CONCAT(',', tags, ','), ',programming-languages,', ',ai-for-math,'))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('programming-languages', tags)
   AND NOT FIND_IN_SET('ai-for-math', tags);
-- protein-design -> proteins
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM
               REPLACE(
                 REPLACE(CONCAT(',', tags, ','), ',protein-design,', ','),
                 ',,', ','))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('protein-design', tags)
   AND FIND_IN_SET('proteins', tags);
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM REPLACE(CONCAT(',', tags, ','), ',protein-design,', ',proteins,'))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('protein-design', tags)
   AND NOT FIND_IN_SET('proteins', tags);
-- quantum -> quantum-computing
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM
               REPLACE(
                 REPLACE(CONCAT(',', tags, ','), ',quantum,', ','),
                 ',,', ','))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('quantum', tags)
   AND FIND_IN_SET('quantum-computing', tags);
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM REPLACE(CONCAT(',', tags, ','), ',quantum,', ',quantum-computing,'))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('quantum', tags)
   AND NOT FIND_IN_SET('quantum-computing', tags);
-- quantum-advantage -> quantum-computing
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM
               REPLACE(
                 REPLACE(CONCAT(',', tags, ','), ',quantum-advantage,', ','),
                 ',,', ','))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('quantum-advantage', tags)
   AND FIND_IN_SET('quantum-computing', tags);
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM REPLACE(CONCAT(',', tags, ','), ',quantum-advantage,', ',quantum-computing,'))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('quantum-advantage', tags)
   AND NOT FIND_IN_SET('quantum-computing', tags);
-- quantum-noise -> quantum-computing
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM
               REPLACE(
                 REPLACE(CONCAT(',', tags, ','), ',quantum-noise,', ','),
                 ',,', ','))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('quantum-noise', tags)
   AND FIND_IN_SET('quantum-computing', tags);
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM REPLACE(CONCAT(',', tags, ','), ',quantum-noise,', ',quantum-computing,'))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('quantum-noise', tags)
   AND NOT FIND_IN_SET('quantum-computing', tags);
-- quantum-physics -> physics
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM
               REPLACE(
                 REPLACE(CONCAT(',', tags, ','), ',quantum-physics,', ','),
                 ',,', ','))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('quantum-physics', tags)
   AND FIND_IN_SET('physics', tags);
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM REPLACE(CONCAT(',', tags, ','), ',quantum-physics,', ',physics,'))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('quantum-physics', tags)
   AND NOT FIND_IN_SET('physics', tags);
-- qubit -> quantum-computing
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM
               REPLACE(
                 REPLACE(CONCAT(',', tags, ','), ',qubit,', ','),
                 ',,', ','))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('qubit', tags)
   AND FIND_IN_SET('quantum-computing', tags);
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM REPLACE(CONCAT(',', tags, ','), ',qubit,', ',quantum-computing,'))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('qubit', tags)
   AND NOT FIND_IN_SET('quantum-computing', tags);
-- qubits -> quantum-computing
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM
               REPLACE(
                 REPLACE(CONCAT(',', tags, ','), ',qubits,', ','),
                 ',,', ','))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('qubits', tags)
   AND FIND_IN_SET('quantum-computing', tags);
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM REPLACE(CONCAT(',', tags, ','), ',qubits,', ',quantum-computing,'))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('qubits', tags)
   AND NOT FIND_IN_SET('quantum-computing', tags);
-- rare-earth -> physics
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM
               REPLACE(
                 REPLACE(CONCAT(',', tags, ','), ',rare-earth,', ','),
                 ',,', ','))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('rare-earth', tags)
   AND FIND_IN_SET('physics', tags);
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM REPLACE(CONCAT(',', tags, ','), ',rare-earth,', ',physics,'))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('rare-earth', tags)
   AND NOT FIND_IN_SET('physics', tags);
-- research -> ai-for-science
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM
               REPLACE(
                 REPLACE(CONCAT(',', tags, ','), ',research,', ','),
                 ',,', ','))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('research', tags)
   AND FIND_IN_SET('ai-for-science', tags);
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM REPLACE(CONCAT(',', tags, ','), ',research,', ',ai-for-science,'))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('research', tags)
   AND NOT FIND_IN_SET('ai-for-science', tags);
-- reward-hacking -> ai-safety
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM
               REPLACE(
                 REPLACE(CONCAT(',', tags, ','), ',reward-hacking,', ','),
                 ',,', ','))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('reward-hacking', tags)
   AND FIND_IN_SET('ai-safety', tags);
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM REPLACE(CONCAT(',', tags, ','), ',reward-hacking,', ',ai-safety,'))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('reward-hacking', tags)
   AND NOT FIND_IN_SET('ai-safety', tags);
-- safety -> ai-safety
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM
               REPLACE(
                 REPLACE(CONCAT(',', tags, ','), ',safety,', ','),
                 ',,', ','))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('safety', tags)
   AND FIND_IN_SET('ai-safety', tags);
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM REPLACE(CONCAT(',', tags, ','), ',safety,', ',ai-safety,'))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('safety', tags)
   AND NOT FIND_IN_SET('ai-safety', tags);
-- science -> ai-for-science
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM
               REPLACE(
                 REPLACE(CONCAT(',', tags, ','), ',science,', ','),
                 ',,', ','))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('science', tags)
   AND FIND_IN_SET('ai-for-science', tags);
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM REPLACE(CONCAT(',', tags, ','), ',science,', ',ai-for-science,'))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('science', tags)
   AND NOT FIND_IN_SET('ai-for-science', tags);
-- science-automation -> ai-for-science
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM
               REPLACE(
                 REPLACE(CONCAT(',', tags, ','), ',science-automation,', ','),
                 ',,', ','))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('science-automation', tags)
   AND FIND_IN_SET('ai-for-science', tags);
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM REPLACE(CONCAT(',', tags, ','), ',science-automation,', ',ai-for-science,'))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('science-automation', tags)
   AND NOT FIND_IN_SET('ai-for-science', tags);
-- scientific-computing -> ai-for-science
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM
               REPLACE(
                 REPLACE(CONCAT(',', tags, ','), ',scientific-computing,', ','),
                 ',,', ','))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('scientific-computing', tags)
   AND FIND_IN_SET('ai-for-science', tags);
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM REPLACE(CONCAT(',', tags, ','), ',scientific-computing,', ',ai-for-science,'))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('scientific-computing', tags)
   AND NOT FIND_IN_SET('ai-for-science', tags);
-- scientific-discovery -> ai-for-science
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM
               REPLACE(
                 REPLACE(CONCAT(',', tags, ','), ',scientific-discovery,', ','),
                 ',,', ','))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('scientific-discovery', tags)
   AND FIND_IN_SET('ai-for-science', tags);
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM REPLACE(CONCAT(',', tags, ','), ',scientific-discovery,', ',ai-for-science,'))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('scientific-discovery', tags)
   AND NOT FIND_IN_SET('ai-for-science', tags);
-- scientific-ml -> ai-for-science
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM
               REPLACE(
                 REPLACE(CONCAT(',', tags, ','), ',scientific-ml,', ','),
                 ',,', ','))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('scientific-ml', tags)
   AND FIND_IN_SET('ai-for-science', tags);
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM REPLACE(CONCAT(',', tags, ','), ',scientific-ml,', ',ai-for-science,'))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('scientific-ml', tags)
   AND NOT FIND_IN_SET('ai-for-science', tags);
-- self-supervised-learning -> generative-models
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM
               REPLACE(
                 REPLACE(CONCAT(',', tags, ','), ',self-supervised-learning,', ','),
                 ',,', ','))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('self-supervised-learning', tags)
   AND FIND_IN_SET('generative-models', tags);
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM REPLACE(CONCAT(',', tags, ','), ',self-supervised-learning,', ',generative-models,'))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('self-supervised-learning', tags)
   AND NOT FIND_IN_SET('generative-models', tags);
-- seti -> space
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM
               REPLACE(
                 REPLACE(CONCAT(',', tags, ','), ',seti,', ','),
                 ',,', ','))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('seti', tags)
   AND FIND_IN_SET('space', tags);
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM REPLACE(CONCAT(',', tags, ','), ',seti,', ',space,'))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('seti', tags)
   AND NOT FIND_IN_SET('space', tags);
-- simulation-hypothesis -> consciousness
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM
               REPLACE(
                 REPLACE(CONCAT(',', tags, ','), ',simulation-hypothesis,', ','),
                 ',,', ','))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('simulation-hypothesis', tags)
   AND FIND_IN_SET('consciousness', tags);
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM REPLACE(CONCAT(',', tags, ','), ',simulation-hypothesis,', ',consciousness,'))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('simulation-hypothesis', tags)
   AND NOT FIND_IN_SET('consciousness', tags);
-- spiking-neural-network -> neuromorphic
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM
               REPLACE(
                 REPLACE(CONCAT(',', tags, ','), ',spiking-neural-network,', ','),
                 ',,', ','))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('spiking-neural-network', tags)
   AND FIND_IN_SET('neuromorphic', tags);
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM REPLACE(CONCAT(',', tags, ','), ',spiking-neural-network,', ',neuromorphic,'))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('spiking-neural-network', tags)
   AND NOT FIND_IN_SET('neuromorphic', tags);
-- stdp -> neuromorphic
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM
               REPLACE(
                 REPLACE(CONCAT(',', tags, ','), ',stdp,', ','),
                 ',,', ','))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('stdp', tags)
   AND FIND_IN_SET('neuromorphic', tags);
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM REPLACE(CONCAT(',', tags, ','), ',stdp,', ',neuromorphic,'))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('stdp', tags)
   AND NOT FIND_IN_SET('neuromorphic', tags);
-- swarm-robotics -> robotics
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM
               REPLACE(
                 REPLACE(CONCAT(',', tags, ','), ',swarm-robotics,', ','),
                 ',,', ','))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('swarm-robotics', tags)
   AND FIND_IN_SET('robotics', tags);
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM REPLACE(CONCAT(',', tags, ','), ',swarm-robotics,', ',robotics,'))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('swarm-robotics', tags)
   AND NOT FIND_IN_SET('robotics', tags);
-- swarms -> robotics
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM
               REPLACE(
                 REPLACE(CONCAT(',', tags, ','), ',swarms,', ','),
                 ',,', ','))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('swarms', tags)
   AND FIND_IN_SET('robotics', tags);
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM REPLACE(CONCAT(',', tags, ','), ',swarms,', ',robotics,'))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('swarms', tags)
   AND NOT FIND_IN_SET('robotics', tags);
-- tfus -> bci
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM
               REPLACE(
                 REPLACE(CONCAT(',', tags, ','), ',tfus,', ','),
                 ',,', ','))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('tfus', tags)
   AND FIND_IN_SET('bci', tags);
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM REPLACE(CONCAT(',', tags, ','), ',tfus,', ',bci,'))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('tfus', tags)
   AND NOT FIND_IN_SET('bci', tags);
-- thermodynamics -> physics
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM
               REPLACE(
                 REPLACE(CONCAT(',', tags, ','), ',thermodynamics,', ','),
                 ',,', ','))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('thermodynamics', tags)
   AND FIND_IN_SET('physics', tags);
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM REPLACE(CONCAT(',', tags, ','), ',thermodynamics,', ',physics,'))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('thermodynamics', tags)
   AND NOT FIND_IN_SET('physics', tags);
-- tryptophan -> neuroscience
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM
               REPLACE(
                 REPLACE(CONCAT(',', tags, ','), ',tryptophan,', ','),
                 ',,', ','))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('tryptophan', tags)
   AND FIND_IN_SET('neuroscience', tags);
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM REPLACE(CONCAT(',', tags, ','), ',tryptophan,', ',neuroscience,'))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('tryptophan', tags)
   AND NOT FIND_IN_SET('neuroscience', tags);
-- ultrasound -> bci
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM
               REPLACE(
                 REPLACE(CONCAT(',', tags, ','), ',ultrasound,', ','),
                 ',,', ','))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('ultrasound', tags)
   AND FIND_IN_SET('bci', tags);
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM REPLACE(CONCAT(',', tags, ','), ',ultrasound,', ',bci,'))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('ultrasound', tags)
   AND NOT FIND_IN_SET('bci', tags);
-- uncanny-valley -> generative-models
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM
               REPLACE(
                 REPLACE(CONCAT(',', tags, ','), ',uncanny-valley,', ','),
                 ',,', ','))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('uncanny-valley', tags)
   AND FIND_IN_SET('generative-models', tags);
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM REPLACE(CONCAT(',', tags, ','), ',uncanny-valley,', ',generative-models,'))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('uncanny-valley', tags)
   AND NOT FIND_IN_SET('generative-models', tags);
-- wearable -> bci
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM
               REPLACE(
                 REPLACE(CONCAT(',', tags, ','), ',wearable,', ','),
                 ',,', ','))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('wearable', tags)
   AND FIND_IN_SET('bci', tags);
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM REPLACE(CONCAT(',', tags, ','), ',wearable,', ',bci,'))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('wearable', tags)
   AND NOT FIND_IN_SET('bci', tags);
-- working-memory -> neuroscience
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM
               REPLACE(
                 REPLACE(CONCAT(',', tags, ','), ',working-memory,', ','),
                 ',,', ','))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('working-memory', tags)
   AND FIND_IN_SET('neuroscience', tags);
UPDATE headlines
   SET tags = TRIM(BOTH ',' FROM REPLACE(CONCAT(',', tags, ','), ',working-memory,', ',neuroscience,'))
 WHERE tags IS NOT NULL
   AND FIND_IN_SET('working-memory', tags)
   AND NOT FIND_IN_SET('neuroscience', tags);

-- After the per-alias passes, a row whose only tag was a (now-deleted) alias
-- can be left with an empty string. Normalize those back to NULL for parity
-- with what the POST path stores.
UPDATE headlines SET tags = NULL WHERE tags = '';

-- ---------------------------------------------------------------------------
-- 4. Verification queries (read-only). Run after the apply and confirm:
--    * the first SELECT returns 0 (no rows still carry an unresolved alias).
--    * the second SELECT returns the canonical-tag histogram you expect.
-- ---------------------------------------------------------------------------
-- SELECT COUNT(*) AS rows_with_unresolved_aliases
--   FROM headlines h
--   JOIN tag_aliases a ON FIND_IN_SET(a.alias_slug, h.tags)
--  WHERE a.alias_slug <> a.canonical_slug;
--
-- SELECT a.canonical_slug, COUNT(DISTINCT h.id) AS articles
--   FROM headlines h
--   JOIN tag_aliases a ON FIND_IN_SET(a.alias_slug, h.tags)
--  WHERE a.alias_slug = a.canonical_slug
--  GROUP BY a.canonical_slug
--  ORDER BY articles DESC;

