"""
Generate docs/migrations/0004_normalize_tags.sql from config/canonical_tags.json.

Run from the repo root:

    python docs/migrations/gen_0004_normalize_tags.py

Output is pure SQL designed to run cleanly in phpMyAdmin on Namecheap shared
hosting (no CLI / no SSH / no CREATE ROUTINE required).

Why a regenerator: 0004 is just a mechanical projection of the alias map. When
config/canonical_tags.json changes, regenerate; do not hand-edit the SQL.

Idempotence strategy in the generated SQL:
  * CREATE TABLE IF NOT EXISTS tag_aliases    -- no-op on re-run.
  * REPLACE INTO tag_aliases ...              -- primary key is alias_slug,
    so re-runs overwrite identical rows; safe to re-apply.
  * Headlines.tags lower-cased once up front  -- no-op once already lowercase.
  * Each per-alias UPDATE is FIND_IN_SET-guarded -- after the first apply,
    FIND_IN_SET returns 0 and the WHERE clause prunes the row, so ROW_COUNT()=0.

Dedup is handled inline: for each alias, two UPDATEs run. When the row already
carries the canonical, the alias is *deleted* from the CSV rather than
REPLACE-d, so 'memristor,neuromorphic' becomes 'neuromorphic', not
'neuromorphic,neuromorphic'.

Case-sensitivity: REPLACE() is byte-exact while FIND_IN_SET is
collation-insensitive, so the generated SQL lower-cases headlines.tags up
front (Step 2b) to eliminate that mismatch.

Collation: tag_aliases is pinned to utf8mb4_unicode_ci because that is the
collation headlines (and digests) use in production -- verified via
information_schema on 2026-06-05. Any new auxiliary table in this database
should also use utf8mb4_unicode_ci so cross-table FIND_IN_SET / JOIN clauses
do not need an explicit COLLATE on every reference.
"""
import json
from pathlib import Path

# Repo root = the directory two levels up from this file (docs/migrations/...).
REPO = Path(__file__).resolve().parent.parent.parent
ALIAS_JSON = REPO / 'config' / 'canonical_tags.json'
OUT_SQL = REPO / 'docs' / 'migrations' / '0004_normalize_tags.sql'

cfg = json.loads(ALIAS_JSON.read_text(encoding='utf-8'))
aliases = cfg['aliases']

def sql_str(s: str) -> str:
    return "'" + s.replace("'", "''") + "'"

rows = sorted(aliases.items())
canonicals = sorted({c['slug'] for c in cfg['canonical_tags']})

# Sanity: every alias target is a real canonical slug.
canon_set = set(canonicals)
bad = [(a, c) for a, c in rows if c not in canon_set]
assert not bad, f"bad alias targets: {bad}"

lines = []
lines.append("-- Migration 0004 -- normalize headlines.tags through the canonical alias map.")
lines.append("-- SIG-181 (B4 of the SIG-174 plan).")
lines.append("--")
lines.append("-- Generated from config/canonical_tags.json. Do not edit this file by hand --")
lines.append("-- update the JSON and re-run docs/migrations/gen_sql_migration.py instead.")
lines.append("--")
lines.append("-- Runs in phpMyAdmin / mysql client. No CLI, no SSH, no stored procedure,")
lines.append("-- no CREATE ROUTINE privilege required.")
lines.append("--")
lines.append("-- Idempotence:")
lines.append("--   * tag_aliases create / populate is no-op on re-run.")
lines.append("--   * The headlines.tags case-fold pre-pass is no-op once tags is already lowercase.")
lines.append("--   * Each per-alias UPDATE is guarded by FIND_IN_SET(<alias>, tags), which")
lines.append("--     returns 0 after the first successful apply, so re-runs update 0 rows.")
lines.append("--")
lines.append("-- Case-sensitivity defect handled here (board feedback, 2026-06-04 verify):")
lines.append("--   FIND_IN_SET is collation-insensitive on the standard ci collations, but")
lines.append("--   REPLACE is byte-exact. Without normalization, mixed-case alias tags")
lines.append("--   ('IIT', 'tFUS', 'NDE') would pass the FIND_IN_SET guard but be skipped")
lines.append("--   by REPLACE, leaving the row mid-normalization. We lower-case headlines.tags")
lines.append("--   up front so every subsequent REPLACE matches every tag the guard sees.")
lines.append("--")
lines.append("-- Collation alignment (board correction, 2026-06-05 verify):")
lines.append("--   information_schema ground truth: headlines.tags is utf8mb4_unicode_ci")
lines.append("--   (the 249-row production table holds non-ASCII content). tag_aliases is")
lines.append("--   pinned here to match, so cross-table joins (FIND_IN_SET(a.alias_slug,")
lines.append("--   h.tags), and the clustering queries the SSCI Digest Editor will run later)")
lines.append("--   do not need an explicit COLLATE clause. Step 1b retro-fixes any existing")
lines.append("--   deployment that picked up a different collation from the server default.")
lines.append("--   (The earlier PR #12 had this inverted -- pinning to general_ci preserved")
lines.append("--   the very mismatch the step was supposed to remove.)")
lines.append("--")
lines.append("-- Dedup during migration: for each alias -> canonical, we run two UPDATEs.")
lines.append("--   (a) If a row contains BOTH the alias and the canonical, delete the alias")
lines.append("--       (so 'memristor,neuromorphic' becomes 'neuromorphic', not")
lines.append("--       'neuromorphic,neuromorphic').")
lines.append("--   (b) Otherwise, REPLACE the alias with the canonical in place.")
lines.append("-- Both UPDATEs are FIND_IN_SET-guarded, so each is independently a no-op")
lines.append("-- once it has been applied, and the (a)/(b) split is mutually exclusive on")
lines.append("-- any given row.")
lines.append("")
lines.append("USE oddimfjz_headlinestore;")
lines.append("")
lines.append("-- ---------------------------------------------------------------------------")
lines.append("-- 1. tag_aliases table.")
lines.append("-- ---------------------------------------------------------------------------")
lines.append("CREATE TABLE IF NOT EXISTS tag_aliases (")
lines.append("  alias_slug     VARCHAR(100) NOT NULL,")
lines.append("  canonical_slug VARCHAR(100) NOT NULL,")
lines.append("  PRIMARY KEY (alias_slug),")
lines.append("  KEY idx_canonical_slug (canonical_slug)")
lines.append(") ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;")
lines.append("")
lines.append("-- 1b. Retro-fix the collation in case the table was created earlier under a")
lines.append("--     different server default (the original prod apply on 2026-06-04 picked")
lines.append("--     up utf8mb4_general_ci against a headlines table on utf8mb4_unicode_ci,")
lines.append("--     which made cross-table FIND_IN_SET fail without explicit COLLATE clauses.)")
lines.append("--     No-op when already aligned.")
lines.append("ALTER TABLE tag_aliases CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;")
lines.append("")
lines.append("-- ---------------------------------------------------------------------------")
lines.append("-- 2. Populate tag_aliases. REPLACE INTO is idempotent: the primary key is the")
lines.append("--    alias slug, so re-runs overwrite identical rows in place.")
lines.append("-- ---------------------------------------------------------------------------")
lines.append("REPLACE INTO tag_aliases (alias_slug, canonical_slug) VALUES")
value_rows = [f"  ({sql_str(a)}, {sql_str(c)})" for a, c in rows]
lines.append(",\n".join(value_rows) + ";")
lines.append("")
lines.append("-- ---------------------------------------------------------------------------")
lines.append("-- 2b. Case-fold headlines.tags so REPLACE matches every alias FIND_IN_SET")
lines.append("--     sees. BINARY makes the inequality byte-exact (the column's default")
lines.append("--     collation would treat 'IIT' and 'iit' as equal and skip the update).")
lines.append("--     Re-runs are no-ops because tags is already lowercase after the first")
lines.append("--     successful apply.")
lines.append("-- ---------------------------------------------------------------------------")
lines.append("UPDATE headlines")
lines.append("   SET tags = LOWER(tags)")
lines.append(" WHERE tags IS NOT NULL")
lines.append("   AND BINARY tags <> BINARY LOWER(tags);")
lines.append("")
lines.append("-- ---------------------------------------------------------------------------")
lines.append("-- 3. Rewrite tags. Two UPDATEs per non-trivial alias (alias != canonical):")
lines.append("--    (a) BOTH alias and canonical present -> delete the alias (dedup).")
lines.append("--    (b) Only the alias is present -> REPLACE alias with canonical.")
lines.append("--    Comma-anchored everywhere so 'kv-cache' never matches 'mega-kv-cache-x'.")
lines.append("--    Both are FIND_IN_SET-guarded so they are independently no-ops on re-run.")
lines.append("-- ---------------------------------------------------------------------------")

non_trivial = [(a, c) for a, c in rows if a != c]
for alias, canon in non_trivial:
    # (a) dedup: row has BOTH alias and canonical -> remove the alias.
    #     ',alias,' -> ',' (then collapse any resulting ',,' -> ',', then TRIM).
    lines.append(
        f"-- {alias} -> {canon}\n"
        f"UPDATE headlines\n"
        f"   SET tags = TRIM(BOTH ',' FROM\n"
        f"               REPLACE(\n"
        f"                 REPLACE(CONCAT(',', tags, ','), ',{alias},', ','),\n"
        f"                 ',,', ','))\n"
        f" WHERE tags IS NOT NULL\n"
        f"   AND FIND_IN_SET({sql_str(alias)}, tags)\n"
        f"   AND FIND_IN_SET({sql_str(canon)}, tags);"
    )
    # (b) replace: row has alias but NOT canonical -> swap in place.
    lines.append(
        f"UPDATE headlines\n"
        f"   SET tags = TRIM(BOTH ',' FROM REPLACE(CONCAT(',', tags, ','), "
        f"',{alias},', ',{canon},'))\n"
        f" WHERE tags IS NOT NULL\n"
        f"   AND FIND_IN_SET({sql_str(alias)}, tags)\n"
        f"   AND NOT FIND_IN_SET({sql_str(canon)}, tags);"
    )

lines.append("")
lines.append("-- After the per-alias passes, a row whose only tag was a (now-deleted) alias")
lines.append("-- can be left with an empty string. Normalize those back to NULL for parity")
lines.append("-- with what the POST path stores.")
lines.append("UPDATE headlines SET tags = NULL WHERE tags = '';")
lines.append("")
lines.append("-- ---------------------------------------------------------------------------")
lines.append("-- 4. Verification queries (read-only). Run after the apply and confirm:")
lines.append("--    * the first SELECT returns 0 (no rows still carry an unresolved alias).")
lines.append("--    * the second SELECT returns the canonical-tag histogram you expect.")
lines.append("-- ---------------------------------------------------------------------------")
lines.append("-- SELECT COUNT(*) AS rows_with_unresolved_aliases")
lines.append("--   FROM headlines h")
lines.append("--   JOIN tag_aliases a ON FIND_IN_SET(a.alias_slug, h.tags)")
lines.append("--  WHERE a.alias_slug <> a.canonical_slug;")
lines.append("--")
lines.append("-- SELECT a.canonical_slug, COUNT(DISTINCT h.id) AS articles")
lines.append("--   FROM headlines h")
lines.append("--   JOIN tag_aliases a ON FIND_IN_SET(a.alias_slug, h.tags)")
lines.append("--  WHERE a.alias_slug = a.canonical_slug")
lines.append("--  GROUP BY a.canonical_slug")
lines.append("--  ORDER BY articles DESC;")
lines.append("")

OUT_SQL.write_text("\n".join(lines) + "\n", encoding='utf-8')
print(f"wrote {OUT_SQL}")
print(f"  {len(rows)} aliases (including {len(rows) - len(non_trivial)} canonical->canonical no-ops)")
print(f"  {len(non_trivial)} non-trivial UPDATE statements")
print(f"  {len(canonicals)} canonical tags")
